Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -136,13 +136,13 @@ jobs:
             export DOCKER_USERNAME="${DOCKER_USERNAME}"
             export DOCKER_PASSWORD="${DOCKER_PASSWORD}"
 
-            if ! command -v docker &> /dev/null; then
-              echo "Docker not found, installing Docker..."
-              sudo apt update
-              sudo apt install -y docker.io
-              sudo systemctl start docker
-              sudo systemctl enable docker
-            fi
+            # if ! command -v docker &> /dev/null; then
+            #   echo "Docker not found, installing Docker..."
+            #   sudo apt update
+            #   sudo apt install -y docker.io
+            #   sudo systemctl start docker
+            #   sudo systemctl enable docker
+            # fi
 
             # Login to Docker
             echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
