Update cicd.yml

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -73,28 +73,30 @@ jobs:
         run: |
           terraform output -raw instance_public_ip
 
-      - name: Extract and Write IP to File
+      - name: Output Instance IP
+        id: ec2_ip
         working-directory: terraform
         run: |
           ip=$(terraform output -raw instance_public_ip)
-          echo "Extracted IP: $ip"  # Debugging line to print the IP
-          echo "$ip" > ec2_ip.txt
+          echo "Extracted IP: $ip"  # Debugging line
+          echo "$ip" > /tmp/ec2_ip.txt
 
       - name: Verify IP in Temporary File
-        working-directory: terraform
         run: |
-          echo "Contents of ec2_ip.txt:"
-          cat ec2_ip.txt
+          echo "Contents of /tmp/ec2_ip.txt:"
+          cat /tmp/ec2_ip.txt
+
       - name: Set EC2 IP in Environment
         id: set_env_ip
         run: |
-          echo "ec2_ip=$(cat ec2_ip.txt)" >> $GITHUB_ENV
-          echo "::set-output name=ec2_ip::$(cat ec2_ip.txt)"
-  
-   
-  
-
-
+          if [ -f /tmp/ec2_ip.txt ]; then
+          echo "ec2_ip=$(cat /tmp/ec2_ip.txt)" >> $GITHUB_ENV
+          echo "::set-output name=ec2_ip::$(cat /tmp/ec2_ip.txt)"
+          else
+          echo "Error: /tmp/ec2_ip.txt does not exist" >&2
+          exit 1
+          fi
+          
   deploy_to_ec2:
     runs-on: ubuntu-latest
     needs: terraform
